spring:
  thymeleaf:
    cache: false   #设置thymeleaf缓存
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/woha?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    main:
      allow-circular-references: true
  mybatis-plus:
    type-aliases-package: com.starQeem.pojo
logging:
  level:
    com:
      starQeem: debug  #日志处理